force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>销售订单</description>
    <label>Sales Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>14</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/LwcStudyOrderList.cls
public with sharing class LwcStudyOrderList {

    @AuraEnabled
    public static String OrderList(){
        // 查询所有salesOrder
        List<Sales_Order__c> OrderList = [SELECT 
        Id,
        Name,
        Order_Type__c,
        Price__c,
        Approval_Status__c
        FROM Sales_Order__c ];   
        String str = JSON.serialize(OrderList);
        return str;
    }

    @AuraEnabled
    public static String OrderSerch(String name,String type,String price,String approvalStatus){
        String querySql = 'select Id,Name,Order_Type__c,Price__c,Approval_Status__c from Sales_Order__c';
        String queryFitler = '';
       if(String.isNotBlank(name)){
           String nameStr = '%'+name+'%';
           queryFitler += ' and Name like :nameStr'; 
       }
       if(String.isNotBlank(type)){
        queryFitler += ' and Order_Type__c =:type';
       }
       if(String.isNotBlank(price)){       
        Decimal price2 = Decimal.valueOf(price);
        queryFitler += ' and Price__c =:price2';
       }
       if(String.isNotBlank(approvalStatus)){
        queryFitler += ' and Approval_Status__c =:approvalStatus';
       }
       if(String.isNotBlank(queryFitler)){
           querySql += ' WHERE ' + queryFitler.removeStart(' and ');
       }
       System.debug(querySql);
       List<Sales_Order__c> OrderList = Database.Query(querySql);
       System.debug(OrderList);
       String str = JSON.serialize(OrderList);
        return str;
    }
}